### ISSUE TITLE
Add pull request template ?

### ISSUE THREAD

**Issue by Grenadingue** [Grenadingue/messy-politics#7]
Like [this one](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) ?

What is a pull request template ? https://github.com/blog/2111-issue-and-pull-request-templates

How to create a pull request template ? https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by tomacf** [comment]
I'm scared that a too exigent contributing process will slow down any community contribution.
If you agree, I will put some line on the contributing.md about the pull request format, but it will just be something simple, more like a "recommendation" than an "obligation".
If a pull request format is too far from what we can accept, we will just have to refuse it and redirect the contributor to our guidelines.

**Comment by Grenadingue** [comment]
I agree with that
